on:
  schedule:
    # every week
    - cron: 0 0 * * 0

  workflow_dispatch:

jobs:
  update_animes:
    runs-on: ubuntu-latest
    name: Updates README Anime List
    steps:
      - uses: actions/checkout@v2
      - uses: glup3/anilist-animes-action@v1.0.4
        with:
          ANILIST_USERNAME: 'strikeraryu'
          HEADER_TITLE: "My Anime List"